name: Release
permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  id-token: none
  issues: read
  discussions: read
  packages: write
  pages: write
  pull-requests: read
  repository-projects: write
  security-events: read
  statuses: read
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 // 官方要求

      - name: Set up Go
        uses: actions/setup-go@v5
        with: 
          go-version-file: "go.mod"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} // 使用 github-actions 发布